version: "3"

services:
    django: &django
        container_name: noodle_django
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PROJECT_DIR: ${PROJECT_DIR}
        env_file: .env
        ports:
            - "8000:8000"
        volumes:
            - ./static:${PROJECT_DIR}/static
            - ./media:${PROJECT_DIR}/media
            - .:${PROJECT_DIR}
        depends_on:
            - postgres
            - redis

    postgres:
        container_name: noodle_postgres
        image: postgres:15.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env

    redis:
        container_name: noodle_redis
        image: redis:alpine

    celery: &celery
        <<: *django
        container_name: noodle_celery
        entrypoint: [ "/bin/bash", "shell_scripts/celery_start.sh" ]
        volumes:
            - .:/app
        ports: [ ]
        depends_on:
            - redis
            - django
            - postgres

    beat:
        <<: *celery
        container_name: noodle_beat
        entrypoint: [ "/bin/sh", "shell_scripts/beat_start.sh" ]

    flower:
        <<: *django
        container_name: noodle_flower
        ports:
            - "5555:5555"
        entrypoint: [ "/bin/bash", "shell_scripts/flower_start.sh" ]

volumes:
    postgres_data: