# Generated by Django 4.1.5 on 2023-01-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=264)),
                ('users_count', models.BigIntegerField()),
            ],
        ),
    ]
