# Generated by Django 4.1.5 on 2023-01-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkgroup',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='vkgroup',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
