# Generated by Django 4.1.5 on 2023-01-19 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vk_integration', '0002_remove_vkgroup_group_id_alter_vkgroup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vkgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
